base_url = "https://bano.dev"
title = "Bano's Nook"

theme = "duckquill"

compile_sass = true
minify_html = true
# generate_feed = true
# feed_filenames = ["atom.xml"]

taxonomies = [
  # {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[extra]
accent_color = "#ff7800"
primary_color_alpha = "rgba(255, 120, 0, 0.2)"
accent_color_dark = "#ffa348"
primary_color_dark_alpha = "rgba(255, 163, 72, 0.2)"
issues_url = "https://github.com/banonotit/banonotit.github.io/issues"
source_url = "https://github.com/banonotit/banonotit.github.io"
styles = ["custom.css"]
show_read_time = true

[extra.nav]
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  # { url = "@/use.md", name = "/use" },
  { url = "@/now.md", name = "Status" },

  # { url = "https://mastodon.ml/@bano", name = "Mastodon" },
  # { url = "https://codeberg.org/bano", name = "Codeberg" },
  # { url = "https://github.com/banonotit", name = "GitHub" },
  # { url = "mailto:REMOVE-TO-NOT-GET-INTO-SPAM-me@bano.dev", name = "Email" },
]

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = true

[extra.comments]
host = "mastodon.ml"
user = "bano"
